export interface TreatmentItem {
  slug: string;
  nameEn: string;
  nameHi: string;
  category: string;
  description: string;
  whenToSeekCare: string;
  medicalNote?: string;
  isSeriousCondition?: boolean;
}

export const clinicConfig = {
  name: 'DR. Q.H. KHAN CLASSICAL HOMOEOPATHIC CLINIC',
  tagline: 'Classical Homoeopathic Consultation & Healthcare Since 1958',
  establishedYear: 1958,
  address: 'Nagmatia Road, Gaya, Bihar, India',
  city: 'Gaya',
  state: 'Bihar',
  country: 'India',
  helplines: [
    { number: '9709786669', isWhatsapp: false, label: 'Helpline 1' },
    { number: '9135404090', isWhatsapp: true, label: 'Helpline 2 (WhatsApp Available)' },
    { number: '9097211989', isWhatsapp: false, label: 'Helpline 3' },
  ],
  whatsappNumber: '9135404090',
  googleMapsDirectionsUrl:
    'https://www.google.com/maps/search/?api=1&query=Nagmatia+Road+Gaya+Bihar',
  slogans: [
    'मेहनत करने वाले की कभी हार नहीं होती',
    'मेरा काम ही मेरी पहचान है।',
    'बीमारी से डरना नहीं, लड़ना है।',
    'Take Care And Health Care',
    'We Treat God Cure',
    'हमारा परम एवं एकमात्र उद्देश्य',
  ],
  timings: {
    weekdayMorning: '8:00 AM – 12:00 PM',
    weekdayEvening: '2:00 PM – 8:00 PM',
    sundayTiming: 'OPEN (7:00 AM – 12:00 PM & 2:00 PM – 8:00 PM)',
    holidayNote: 'Clinic remains open on Sundays and announced clinic holidays.',
  },
  medicalDisclaimer:
    'The information provided on this website is for general informational purposes and does not replace professional medical diagnosis, treatment or emergency care.',
  emergencyWarning:
    'If you are experiencing severe, sudden or life-threatening symptoms, seek appropriate emergency medical care immediately.',
};

export const treatmentsData: TreatmentItem[] = [
  {
    slug: 'psoriasis',
    nameEn: 'Psoriasis',
    nameHi: 'सोरियासिस',
    category: 'Skin & Dermatology',
    description:
      'Chronic auto-immune skin manifestation characterized by scaly patches, redness, and scalp or extensor surface scaling.',
    whenToSeekCare: 'Consult when skin patches spread, crack, itch intensely, or cause joint pain.',
  },
  {
    slug: 'gray-hair',
    nameEn: 'Gray Hair / Premature Greying',
    nameHi: 'बाल सफेद होना',
    category: 'Trichology & Hair Care',
    description: 'Loss of hair pigment due to nutritional, stress, or constitutional factors.',
    whenToSeekCare: 'Seek evaluation if greying occurs alongside sudden hair loss or scalp inflammation.',
  },
  {
    slug: 'eczema',
    nameEn: 'Eczema',
    nameHi: 'एक्जिमा',
    category: 'Skin & Dermatology',
    description: 'Inflammatory skin condition presenting with itchy, inflamed, and oozing patches.',
    whenToSeekCare: 'Consult if skin breaks open, develops yellow crusting, or disrupts sleep.',
  },
  {
    slug: 'stricture',
    nameEn: 'Stricture (Urethral / Oesophageal)',
    nameHi: 'स्ट्रिक्चर (Stricture)',
    category: 'Urology & Internal Medicine',
    description: 'Abnormal narrowing of a bodily passage leading to restricted fluid flow.',
    whenToSeekCare: 'Urgent evaluation required if experiencing severe urinary obstruction or severe swallowing pain.',
  },
  {
    slug: 'piles',
    nameEn: 'Piles / Haemorrhoids',
    nameHi: 'बवासीर',
    category: 'Anorectal Care',
    description: 'Swollen veins in the lower rectum and anus causing discomfort and rectal bleeding.',
    whenToSeekCare: 'Seek immediate care if rectal bleeding is heavy, persistent, or accompanied by dizziness.',
  },
  {
    slug: 'gland',
    nameEn: 'Glandular Swelling',
    nameHi: 'गिल्टी',
    category: 'Lymphatic & General Medicine',
    description: 'Enlargement of lymph nodes or glandular tissues in response to chronic inflammation.',
    whenToSeekCare: 'Consult if a gland remains hard, painless, rapidly growing, or fixed to surrounding tissue.',
  },
  {
    slug: 'adenoids',
    nameEn: 'Adenoids',
    nameHi: 'नाक और गले के मध्य मांस का बढ़ना',
    category: 'ENT Healthcare',
    description: 'Enlargement of lymphatic tissue behind the nasal cavity causing mouth breathing and snoring.',
    whenToSeekCare: 'Consult if child suffers persistent sleep apnea, recurring ear infections, or breathing difficulty.',
  },
  {
    slug: 'appendicitis',
    nameEn: 'Appendicitis Consultation Support',
    nameHi: 'अपेंडिसाइटिस',
    category: 'Gastroenterology',
    description: 'Inflammation of the appendix tissue.',
    whenToSeekCare: 'CRITICAL EMERGENCY: Acute right lower abdominal pain requires immediate surgical emergency evaluation.',
    medicalNote: 'Emergency acute appendicitis requires immediate hospital evaluation. Do not delay emergency surgical care.',
    isSeriousCondition: true,
  },
  {
    slug: 'corns',
    nameEn: 'Corns & Warts',
    nameHi: 'गट्टे पड़ना / मस्से होना',
    category: 'Skin & Podiatry',
    description: 'Hyperkeratotic skin lesions on feet, hands, or fingers due to friction or viral factors.',
    whenToSeekCare: 'Consult if corns become painful during walking or show signs of ulceration.',
  },
  {
    slug: 'calculi',
    nameEn: 'Calculi (Kidney & Gallbladder Stones)',
    nameHi: 'पथरी रोग (गुर्दे एवं पित्ताशय की पथरी)',
    category: 'Renal & Hepato-Biliary',
    description: 'Mineral deposits formed in the renal tract or gallbladder.',
    whenToSeekCare: 'Seek urgent care if experiencing high fever, persistent vomiting, or inability to pass urine.',
  },
  {
    slug: 'fibroid-tumor',
    nameEn: 'Fibroid Tumor (Uterine Fibroids)',
    nameHi: 'गर्भाशय का फाइब्रॉइड',
    category: 'Gynaecology',
    description: 'Non-cancerous growths of the uterus causing heavy menstrual bleeding or pelvic pressure.',
    whenToSeekCare: 'Consult if experiencing severe pelvic pain, severe anaemia, or heavy prolonged cycles.',
  },
  {
    slug: 'hernia',
    nameEn: 'Hernia Consultation',
    nameHi: 'हर्निया',
    category: 'General Surgery / Consultation',
    description: 'Protrusion of an organ through the wall of the cavity that normally contains it.',
    whenToSeekCare: 'Seek immediate emergency attention if bulge becomes painful, hard, or incarcerated.',
    isSeriousCondition: true,
  },
  {
    slug: 'hydrocele',
    nameEn: 'Hydrocele',
    nameHi: 'हाइड्रोसील',
    category: 'Urology',
    description: 'Fluid accumulation around the testicles causing swelling.',
    whenToSeekCare: 'Consult if scrotal swelling develops suddenly or is accompanied by severe acute pain.',
  },
  {
    slug: 'nodules',
    nameEn: 'Nodules & Cysts',
    nameHi: 'गांठें',
    category: 'General Medicine',
    description: 'Subcutaneous or organ-specific tissue lumps requiring diagnostic evaluation.',
    whenToSeekCare: 'Consult for diagnostic imaging evaluation when any new lump or nodule is discovered.',
  },
  {
    slug: 'otorrhea',
    nameEn: 'Otorrhea (Ear Discharge)',
    nameHi: 'कान से पस आना',
    category: 'ENT Healthcare',
    description: 'Purulent or fluid discharge from the ear canal stemming from otitis media.',
    whenToSeekCare: 'Consult if accompanied by hearing loss, dizziness, or facial numbness.',
  },
  {
    slug: 'dropsy',
    nameEn: 'Dropsy / Oedema',
    nameHi: 'अंगों में जल संचय',
    category: 'Cardio-Renal Medicine',
    description: 'Abnormal accumulation of fluid in bodily tissues causing swelling.',
    whenToSeekCare: 'Seek immediate emergency care if leg swelling occurs alongside shortness of breath or chest pain.',
    isSeriousCondition: true,
  },
  {
    slug: 'synovitis',
    nameEn: 'Synovitis / Knee Swelling',
    nameHi: 'घुटने की सूजन',
    category: 'Orthopaedics & Rheumatology',
    description: 'Inflammation of the synovial membrane lining joint cavities.',
    whenToSeekCare: 'Consult if joint is hot, severely swollen, or unable to bear weight.',
  },
  {
    slug: 'nose-bleed',
    nameEn: 'Nose Bleed / Epistaxis',
    nameHi: 'नाक से रक्तस्राव / नकसीर',
    category: 'ENT Healthcare',
    description: 'Bleeding from nasal mucosal blood vessels.',
    whenToSeekCare: 'Seek urgent care if bleeding exceeds 20 minutes or follows head trauma.',
  },
  {
    slug: 'brights-disease',
    nameEn: 'Renal Care Consultation (Historical: Bright\'s Disease)',
    nameHi: 'गुर्दे संबंधी विकार',
    category: 'Nephrology Consultation',
    description: 'Historical clinical terminology for inflammatory renal conditions.',
    whenToSeekCare: 'Seek nephrology evaluation if experiencing decreased urine output, facial puffiness, or high blood pressure.',
    medicalNote: 'Historical terminology; presented strictly as clinical support information.',
    isSeriousCondition: true,
  },
  {
    slug: 'cancer',
    nameEn: 'Oncology Consultation & Palliative Support',
    nameHi: 'कैंसर सहायता परामर्श',
    category: 'Oncology Support',
    description: 'Homoeopathic supportive care during oncology consultation.',
    whenToSeekCare: 'ALWAYS seek primary evaluation and treatment from qualified oncologists and cancer hospitals.',
    medicalNote: 'We do NOT offer cancer cure guarantees. Emergency oncology conditions require specialized hospital care.',
    isSeriousCondition: true,
  },
  {
    slug: 'uterus-troubles',
    nameEn: 'Uterine & Menstrual Disorders',
    nameHi: 'गर्भाशय संबंधी समस्याएं',
    category: 'Gynaecology',
    description: 'Comprehensive evaluation for dysmenorrhea, PCOD, and uterine weakness.',
    whenToSeekCare: 'Consult if bleeding occurs post-menopause or causes severe pelvic distress.',
  },
  {
    slug: 'deafness',
    nameEn: 'Hearing Concerns & Tinnitus',
    nameHi: 'बहरेपन से संबंधित शिकायतें',
    category: 'ENT Healthcare',
    description: 'Evaluation for progressive hearing loss, ear fullness, or ringing sounds.',
    whenToSeekCare: 'Consult an audiologist and ENT specialist for sudden onset hearing impairment.',
  },
  {
    slug: 'fissure',
    nameEn: 'Anal Fissure',
    nameHi: 'फिशर',
    category: 'Anorectal Care',
    description: 'Small tear in the mucosal lining of the anus causing intense sharp pain during bowel movements.',
    whenToSeekCare: 'Consult if pain persists for hours post-defecation or bleeding recurs.',
  },
  {
    slug: 'female-infertility',
    nameEn: 'Female Infertility-Related Concerns',
    nameHi: 'स्त्री स्वास्थ्य एवं बंध्यता परामर्श',
    category: 'Reproductive Health',
    description: 'Hormonal and constitutional supportive therapy for female reproductive health.',
    whenToSeekCare: 'Consult after 12 months of unsuccessful conception for thorough hormonal and structural screening.',
  },
  {
    slug: 'prostate-gland',
    nameEn: 'Prostate Gland Concerns (BPH)',
    nameHi: 'प्रोस्टेट संबंधी समस्याएं',
    category: 'Urology',
    description: 'Prostate enlargement leading to urinary frequency, weak stream, or night urination.',
    whenToSeekCare: 'Seek urgent urological attention if completely unable to pass urine.',
  },
  {
    slug: 'arthritis',
    nameEn: 'Arthritis & Joint Pain',
    nameHi: 'गठिया',
    category: 'Rheumatology',
    description: 'Joint degeneration and inflammatory arthritis affecting mobility.',
    whenToSeekCare: 'Consult if joint deformities or systemic fever accompany joint swellings.',
  },
  {
    slug: 'breast-atrophy',
    nameEn: 'Breast Atrophy Concerns',
    nameHi: 'स्तन के आकार में कमी / संबंधित चिंताएं',
    category: 'Women Health',
    description: 'Constitutional consultation for tissue tone changes.',
    whenToSeekCare: 'Seek immediate mammogram and surgical evaluation for any breast lump or skin dimpling.',
    isSeriousCondition: true,
  },
  {
    slug: 'brain-tumor',
    nameEn: 'Brain Tumor Supportive Care',
    nameHi: 'ब्रेन ट्यूमर सहायता परामर्श',
    category: 'Neurology Support',
    description: 'Palliative homoeopathic support alongside neurosurgical care.',
    whenToSeekCare: 'CRITICAL: Brain tumors require specialized neurosurgical and oncology intervention. Immediate hospital care is mandatory for seizures, persistent vomiting, or neurological deficits.',
    medicalNote: 'We do NOT promise brain tumor cures without surgery. Seek immediate neurosurgical emergency care.',
    isSeriousCondition: true,
  },
];
