export type TargetGroup = 'Male' | 'Female' | 'Children' | 'Mental' | 'General';

export interface TreatmentItem {
  slug: string;
  nameEn: string;
  nameHi: string;
  category: string;
  targetGroup?: TargetGroup;
  description: string;
  whenToSeekCare: string;
  medicalNote?: string;
  isSeriousCondition?: boolean;
}

export const clinicConfig = {
  name: 'DR. Q.H. KHAN CLASSICAL HOMOEOPATHIC CLINIC',
  tagline: 'Classical Homoeopathic Consultation & Healthcare Since 1958',
  establishedYear: 1958,
  address: 'Nagmatia Road, Gaya, Bihar, India',
  city: 'Gaya',
  state: 'Bihar',
  country: 'India',
  helplines: [
    { number: '9709786669', isWhatsapp: false, label: 'Helpline 1' },
    { number: '9135404090', isWhatsapp: true, label: 'Helpline 2 (WhatsApp Available)' },
    { number: '9097211989', isWhatsapp: false, label: 'Helpline 3' },
  ],
  whatsappNumber: '9135404090',
  instagramUrl: 'https://www.instagram.com/theqhkhanclinic',
  youtubeUrl: 'https://www.youtube.com/@theqhkhanclinic',
  googleMapsDirectionsUrl:
    'https://www.google.com/maps/search/?api=1&query=Nagmatia+Road+Gaya+Bihar',
  slogans: [
    'मेहनत करने वाले की कभी हार नहीं होती',
    'मेरा काम ही मेरी पहचान है।',
    'बीमारी से डरना नहीं, लड़ना है।',
    'Take Care And Health Care',
    'We Treat God Cure',
    'हमारा परम एवं एकमात्र उद्देश्य',
  ],
  timings: {
    weekdayMorning: '8:00 AM – 12:00 PM',
    weekdayEvening: '2:00 PM – 8:00 PM',
    sundayTiming: 'OPEN (7:00 AM – 12:00 PM & 2:00 PM – 8:00 PM)',
    holidayNote: 'Clinic remains open on Sundays and announced clinic holidays.',
  },
  medicalDisclaimer:
    'The information provided on this website is for general informational purposes and does not replace professional medical diagnosis, treatment or emergency care.',
  emergencyWarning:
    'If you are experiencing severe, sudden or life-threatening symptoms, seek appropriate emergency medical care immediately.',
};

export const treatmentsData: TreatmentItem[] = [
  // --- MALE HEALTH (पुरुष स्वास्थ्य एवं रोग) ---
  {
    slug: 'prostate-gland',
    nameEn: 'Prostate Gland Concerns (BPH)',
    nameHi: 'प्रोस्टेट संबंधी समस्याएं (पुरुष रोग)',
    category: 'Men\'s Health / Urology',
    targetGroup: 'Male',
    description: 'Prostate enlargement leading to urinary frequency, weak stream, hesitance, or night urination.',
    whenToSeekCare: 'Seek urgent urological attention if completely unable to pass urine.',
  },
  {
    slug: 'hydrocele',
    nameEn: 'Hydrocele',
    nameHi: 'हाइड्रोसील (पुरुष स्वास्थ्य)',
    category: 'Men\'s Health / Urology',
    targetGroup: 'Male',
    description: 'Fluid accumulation around the testicles causing heaviness or swelling.',
    whenToSeekCare: 'Consult if scrotal swelling develops suddenly or is accompanied by severe acute pain.',
  },
  {
    slug: 'male-infertility',
    nameEn: 'Male Infertility & Sexual Health',
    nameHi: 'पुरुष बांझपन एवं यौन स्वास्थ्य परामर्श',
    category: 'Men\'s Health / Reproductive Care',
    targetGroup: 'Male',
    description: 'Constitutional homoeopathic evaluation for sperm count issues, motility, and male reproductive vitality.',
    whenToSeekCare: 'Consult after 12 months of unsuccessful conception for semen evaluation and constitutional guidance.',
  },

  // --- FEMALE HEALTH (महिला स्वास्थ्य एवं रोग) ---
  {
    slug: 'female-infertility',
    nameEn: 'Female Infertility & Hormonal Health',
    nameHi: 'स्त्री स्वास्थ्य एवं बंध्यता परामर्श (PCOD/PCOS)',
    category: 'Women\'s Health / Reproductive',
    targetGroup: 'Female',
    description: 'Hormonal, PCOD, and constitutional supportive therapy for female reproductive health and cycle regularity.',
    whenToSeekCare: 'Consult after 12 months of unsuccessful conception or irregular painful cycles.',
  },
  {
    slug: 'uterus-troubles',
    nameEn: 'Uterine & Menstrual Disorders',
    nameHi: 'गर्भाशय संबंधी विकार एवं मासिक धर्म समस्या',
    category: 'Women\'s Health / Gynaecology',
    targetGroup: 'Female',
    description: 'Comprehensive evaluation for dysmenorrhea, PCOD, leucorrhea, and uterine weakness.',
    whenToSeekCare: 'Consult if bleeding occurs post-menopause or causes severe pelvic distress.',
  },
  {
    slug: 'fibroid-tumor',
    nameEn: 'Uterine Fibroids',
    nameHi: 'गर्भाशय का फाइब्रॉइड (महिला स्वास्थ्य)',
    category: 'Women\'s Health / Gynaecology',
    targetGroup: 'Female',
    description: 'Non-cancerous growths of the uterus causing heavy menstrual bleeding, cramping, or pelvic pressure.',
    whenToSeekCare: 'Consult if experiencing severe pelvic pain, severe anaemia, or heavy prolonged cycles.',
  },
  {
    slug: 'breast-atrophy',
    nameEn: 'Breast Atrophy & Tissue Health',
    nameHi: 'स्तन स्वास्थ्य एवं आकार संबंधी चिंताएं',
    category: 'Women\'s Health',
    targetGroup: 'Female',
    description: 'Constitutional consultation for tissue tone changes and glandular health.',
    whenToSeekCare: 'Seek immediate mammogram and surgical evaluation for any breast lump or skin dimpling.',
    isSeriousCondition: true,
  },

  // --- CHILDREN'S HEALTH (बाल रोग एवं शिशु देखभाल) ---
  {
    slug: 'adenoids',
    nameEn: 'Childhood Adenoids & Tonsillitis',
    nameHi: 'बच्चों के एडेनोइड्स और टॉन्सिल (बाल रोग)',
    category: 'Pediatric Care / ENT',
    targetGroup: 'Children',
    description: 'Enlargement of nasal lymphatic tissue causing mouth breathing, snoring, and recurring throat infections in children.',
    whenToSeekCare: 'Consult if child suffers persistent sleep apnea, recurring ear infections, or breathing difficulty.',
  },
  {
    slug: 'bed-wetting',
    nameEn: 'Nocturnal Enuresis (Bed-Wetting in Children)',
    nameHi: 'बच्चों में बिस्तर गीला करना (बिस्तर में पेशाब)',
    category: 'Pediatric Care',
    targetGroup: 'Children',
    description: 'Involuntary urination during sleep in young children due to nervous reflex sensitivity or deep sleep patterns.',
    whenToSeekCare: 'Consult if bed-wetting persists past 5 years of age or causes emotional distress.',
  },
  {
    slug: 'child-growth',
    nameEn: 'Pediatric Growth & Immunity Care',
    nameHi: 'बाल रोग, शारीरिक विकास एवं प्रतिरक्षा देखभाल',
    category: 'Pediatric Care',
    targetGroup: 'Children',
    description: 'Natural constitutional therapy for recurrent colds, slow growth milestones, poor appetite, and weak immunity in kids.',
    whenToSeekCare: 'Consult if child suffers frequent recurrent infections, weight loss, or constitutional weakness.',
  },
  // --- BRAIN & MENTAL HEALTH (मस्तिष्क एवं मानसिक स्वास्थ्य) ---
  {
    slug: 'mental-health',
    nameEn: 'Mental Health, Stress & Depression Care',
    nameHi: 'मानसिक स्वास्थ्य, अवसाद (Depression) एवं तनाव परामर्श',
    category: 'Brain & Mental Health',
    targetGroup: 'Mental',
    description: 'Constitutional homoeopathic care for chronic anxiety, depression, insomnia (sleep disorders), mental fatigue, and emotional distress.',
    whenToSeekCare: 'Seek urgent clinical evaluation if experiencing severe emotional crisis or disorienting psychological distress.',
  },
  {
    slug: 'migraine-brain',
    nameEn: 'Migraine & Brain Health Consultation',
    nameHi: 'माइग्रेन, पुराना सिरदर्द एवं मस्तिष्क संबंधी समस्याएं',
    category: 'Brain & Mental Health',
    targetGroup: 'Mental',
    description: 'Individualized constitutional therapy for chronic migraines, vascular headaches, neuralgic pain, and stress-induced brain fatigue.',
    whenToSeekCare: 'Seek immediate emergency care for sudden severe thunderclap headaches, vision loss, or neurological numbness.',
  },

  // --- GENERAL & SKIN DISEASES (त्वचा एवं सामान्य रोग) ---
  {
    slug: 'psoriasis',
    nameEn: 'Psoriasis',
    nameHi: 'सोरियासिस (त्वचा रोग)',
    category: 'Skin & Dermatology',
    targetGroup: 'General',
    description:
      'Chronic auto-immune skin manifestation characterized by scaly patches, redness, and scalp or extensor surface scaling.',
    whenToSeekCare: 'Consult when skin patches spread, crack, itch intensely, or cause joint pain.',
  },
  {
    slug: 'piles',
    nameEn: 'Piles / Haemorrhoids',
    nameHi: 'बवासीर',
    category: 'Anorectal Care',
    targetGroup: 'General',
    description: 'Swollen veins in the lower rectum and anus causing discomfort, pain, and rectal bleeding.',
    whenToSeekCare: 'Seek immediate care if rectal bleeding is heavy, persistent, or accompanied by dizziness.',
  },
  {
    slug: 'eczema',
    nameEn: 'Eczema',
    nameHi: 'एक्जिमा (खाज-खुजली)',
    category: 'Skin & Dermatology',
    targetGroup: 'General',
    description: 'Inflammatory skin condition presenting with itchy, inflamed, and oozing patches.',
    whenToSeekCare: 'Consult if skin breaks open, develops yellow crusting, or disrupts sleep.',
  },
  {
    slug: 'calculi',
    nameEn: 'Calculi (Kidney & Gallbladder Stones)',
    nameHi: 'पथरी रोग (गुर्दे एवं पित्ताशय की पथरी)',
    category: 'Renal & Hepato-Biliary',
    targetGroup: 'General',
    description: 'Mineral deposits formed in the renal tract or gallbladder causing severe flank or abdominal pain.',
    whenToSeekCare: 'Seek urgent care if experiencing high fever, persistent vomiting, or inability to pass urine.',
  },
  {
    slug: 'gray-hair',
    nameEn: 'Gray Hair / Premature Greying',
    nameHi: 'बाल सफेद होना',
    category: 'Trichology & Hair Care',
    targetGroup: 'General',
    description: 'Loss of hair pigment due to nutritional, stress, or constitutional factors.',
    whenToSeekCare: 'Seek evaluation if greying occurs alongside sudden hair loss or scalp inflammation.',
  },
  {
    slug: 'stricture',
    nameEn: 'Stricture (Urethral / Oesophageal)',
    nameHi: 'स्ट्रिक्चर (Stricture)',
    category: 'Urology & Internal Medicine',
    targetGroup: 'General',
    description: 'Abnormal narrowing of a bodily passage leading to restricted fluid flow.',
    whenToSeekCare: 'Urgent evaluation required if experiencing severe urinary obstruction or severe swallowing pain.',
  },
  {
    slug: 'gland',
    nameEn: 'Glandular Swelling',
    nameHi: 'गिल्टी',
    category: 'Lymphatic & General Medicine',
    targetGroup: 'General',
    description: 'Enlargement of lymph nodes or glandular tissues in response to chronic inflammation.',
    whenToSeekCare: 'Consult if a gland remains hard, painless, rapidly growing, or fixed to surrounding tissue.',
  },
  {
    slug: 'appendicitis',
    nameEn: 'Appendicitis Consultation Support',
    nameHi: 'अपेंडिसाइटिस',
    category: 'Gastroenterology',
    targetGroup: 'General',
    description: 'Inflammation of the appendix tissue.',
    whenToSeekCare: 'CRITICAL EMERGENCY: Acute right lower abdominal pain requires immediate surgical emergency evaluation.',
    medicalNote: 'Emergency acute appendicitis requires immediate hospital evaluation. Do not delay emergency surgical care.',
    isSeriousCondition: true,
  },
  {
    slug: 'corns',
    nameEn: 'Corns & Warts',
    nameHi: 'गट्टे पड़ना / मस्से होना',
    category: 'Skin & Podiatry',
    targetGroup: 'General',
    description: 'Hyperkeratotic skin lesions on feet, hands, or fingers due to friction or viral factors.',
    whenToSeekCare: 'Consult if corns become painful during walking or show signs of ulceration.',
  },
  {
    slug: 'hernia',
    nameEn: 'Hernia Consultation',
    nameHi: 'हर्निया',
    category: 'General Surgery / Consultation',
    targetGroup: 'General',
    description: 'Protrusion of an organ through the wall of the cavity that normally contains it.',
    whenToSeekCare: 'Seek immediate emergency attention if bulge becomes painful, hard, or incarcerated.',
    isSeriousCondition: true,
  },
  {
    slug: 'nodules',
    nameEn: 'Nodules & Cysts',
    nameHi: 'गांठें',
    category: 'General Medicine',
    targetGroup: 'General',
    description: 'Subcutaneous or organ-specific tissue lumps requiring diagnostic evaluation.',
    whenToSeekCare: 'Consult for diagnostic imaging evaluation when any new lump or nodule is discovered.',
  },
  {
    slug: 'otorrhea',
    nameEn: 'Otorrhea (Ear Discharge)',
    nameHi: 'कान से पस आना',
    category: 'ENT Healthcare',
    targetGroup: 'Children',
    description: 'Purulent or fluid discharge from the ear canal stemming from otitis media.',
    whenToSeekCare: 'Consult if accompanied by hearing loss, dizziness, or facial numbness.',
  },
  {
    slug: 'dropsy',
    nameEn: 'Dropsy / Oedema',
    nameHi: 'अंगों में जल संचय',
    category: 'Cardio-Renal Medicine',
    targetGroup: 'General',
    description: 'Abnormal accumulation of fluid in bodily tissues causing swelling.',
    whenToSeekCare: 'Seek immediate emergency care if leg swelling occurs alongside shortness of breath or chest pain.',
    isSeriousCondition: true,
  },
  {
    slug: 'synovitis',
    nameEn: 'Synovitis / Knee Swelling',
    nameHi: 'घुटने की सूजन',
    category: 'Orthopaedics & Rheumatology',
    targetGroup: 'General',
    description: 'Inflammation of the synovial membrane lining joint cavities.',
    whenToSeekCare: 'Consult if joint is hot, severely swollen, or unable to bear weight.',
  },
  {
    slug: 'nose-bleed',
    nameEn: 'Nose Bleed / Epistaxis',
    nameHi: 'नाक से रक्तस्राव / नकसीर',
    category: 'ENT Healthcare',
    targetGroup: 'Children',
    description: 'Bleeding from nasal mucosal blood vessels.',
    whenToSeekCare: 'Seek urgent care if bleeding exceeds 20 minutes or follows head trauma.',
  },
  {
    slug: 'brights-disease',
    nameEn: 'Renal Care Consultation (Historical: Bright\'s Disease)',
    nameHi: 'गुर्दे संबंधी विकार',
    category: 'Nephrology Consultation',
    targetGroup: 'General',
    description: 'Historical clinical terminology for inflammatory renal conditions.',
    whenToSeekCare: 'Seek nephrology evaluation if experiencing decreased urine output, facial puffiness, or high blood pressure.',
    medicalNote: 'Historical terminology; presented strictly as clinical support information.',
    isSeriousCondition: true,
  },
  {
    slug: 'cancer',
    nameEn: 'Oncology Consultation & Palliative Support',
    nameHi: 'कैंसर सहायता परामर्श',
    category: 'Oncology Support',
    targetGroup: 'General',
    description: 'Homoeopathic supportive care during oncology consultation.',
    whenToSeekCare: 'ALWAYS seek primary evaluation and treatment from qualified oncologists and cancer hospitals.',
    medicalNote: 'We do NOT offer cancer cure guarantees. Emergency oncology conditions require specialized hospital care.',
    isSeriousCondition: true,
  },
  {
    slug: 'deafness',
    nameEn: 'Hearing Concerns & Tinnitus',
    nameHi: 'बहरेपन से संबंधित शिकायतें',
    category: 'ENT Healthcare',
    targetGroup: 'General',
    description: 'Evaluation for progressive hearing loss, ear fullness, or ringing sounds.',
    whenToSeekCare: 'Consult an audiologist and ENT specialist for sudden onset hearing impairment.',
  },
  {
    slug: 'fissure',
    nameEn: 'Anal Fissure',
    nameHi: 'फिशर',
    category: 'Anorectal Care',
    targetGroup: 'General',
    description: 'Small tear in the mucosal lining of the anus causing intense sharp pain during bowel movements.',
    whenToSeekCare: 'Consult if pain persists for hours post-defecation or bleeding recurs.',
  },
  {
    slug: 'arthritis',
    nameEn: 'Arthritis & Joint Pain',
    nameHi: 'गठिया (जोड़ों का दर्द)',
    category: 'Rheumatology',
    targetGroup: 'General',
    description: 'Joint degeneration and inflammatory arthritis affecting mobility.',
    whenToSeekCare: 'Consult if joint deformities or systemic fever accompany joint swellings.',
  },
  {
    slug: 'brain-tumor',
    nameEn: 'Brain Tumor Supportive Care',
    nameHi: 'ब्रेन ट्यूमर सहायता परामर्श',
    category: 'Neurology Support',
    targetGroup: 'General',
    description: 'Palliative homoeopathic support alongside neurosurgical care.',
    whenToSeekCare: 'CRITICAL: Brain tumors require specialized neurosurgical and oncology intervention. Immediate hospital care is mandatory for seizures, persistent vomiting, or neurological deficits.',
    medicalNote: 'We do NOT promise brain tumor cures without surgery. Seek immediate neurosurgical emergency care.',
    isSeriousCondition: true,
  },
];

